//
//  UIFont+ZEAdditions.swift
//
//  Generated by Zeplin on 12/11/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {

	@nonobjc class var zeBody17PtRegularWhite: UIFont {
		return UIFont.systemFont(ofSize: 17.0, weight: .regular)
	}

	@nonobjc class var zeBody17PtRegular: UIFont {
		return UIFont.systemFont(ofSize: 17.0, weight: .regular)
	}

	@nonobjc class var zeFootnote13PtRegularGrey: UIFont {
		return UIFont.systemFont(ofSize: 13.0, weight: .regular)
	}
}
