//
//  UIColor+ZEAdditions.swift
//
//  Generated by Zeplin on 12/11/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {

	@nonobjc class var zeGoldenrod: UIColor { 
		return UIColor(red: 247.0 / 255.0, green: 208.0 / 255.0, blue: 10.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var zeBgblack: UIColor { 
		return UIColor(red: 42.0 / 255.0, green: 40.0 / 255.0, blue: 40.0 / 255.0, alpha: 1.0)
	}
}
